site_name: Collateralized Trade on Circle ARC
site_description: DeFi-style trade lifecycle on Circle ARC Testnet using ERC-8183 and ERC-721

docs_dir: .
nav:
  - Home: README.md

theme:
  name: material
  features:
    - navigation.top
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
